# Generated by Django 5.1.7 on 2025-03-24 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductoGranel', '0005_alter_corteinventariogranel_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_negocio', models.CharField(max_length=255)),
                ('giro', models.CharField(max_length=255)),
                ('tipo_exhibidor', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('colonia', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('credito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConcentradoPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_concentrado', models.DateTimeField()),
                ('estado', models.CharField(default='pendiente', help_text='"pendiente", "procesado", "finalizado"', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GramajeProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.CharField(help_text='Ruta de la imagen', max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresentacionProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(help_text='Ruta de la imagen', max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('kilometraje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ultimo_servicio', models.DateTimeField()),
                ('observaciones', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteDiasVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(help_text='Día de la semana (Ej: Lunes, Martes, etc.)', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CorteInventarioPTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(help_text='Fecha del corte')),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(default='pendiente', help_text='"pendiente", "verificado", "ajustado"', max_length=20)),
                ('usuario', models.ForeignKey(help_text='Quién realizó el corte', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaPTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('nota', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.CharField(help_text='Ruta de la imagen', max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.categoriaproducto')),
                ('gramaje_producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.gramajeproductoterminado')),
                ('presentacion_producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.presentacionproductoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEntradaPTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entrada_p_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.entradapterminado')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCorteInventarioPTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_teorico', models.DecimalField(decimal_places=2, help_text='Según las salidas/entradas', max_digits=10)),
                ('stock_real', models.DecimalField(decimal_places=2, help_text='Lo contado físicamente', max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, help_text='stock_real - stock_teorico', max_digits=10)),
                ('ajuste_necesario', models.BooleanField(default=False, help_text='Si se requiere un ajuste en la BD')),
                ('corte_inventario_p_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.corteinventariopterminado')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleConcentradoPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_total', models.DecimalField(decimal_places=2, help_text='Suma de los pedidos de los clientes', max_digits=10)),
                ('concentrado_pedidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.concentradopedidos')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productoterminado')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.ruta')),
            ],
        ),
        migrations.AddField(
            model_name='concentradopedidos',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProductoTerminado.ruta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProductoTerminado.ruta'),
        ),
        migrations.CreateModel(
            name='SalidaPTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField()),
                ('destino', models.CharField(max_length=255)),
                ('nota', models.TextField()),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProductoTerminado.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSalidaPTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productoterminado')),
                ('salida_p_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.salidapterminado')),
            ],
        ),
        migrations.CreateModel(
            name='VentaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField()),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(default='pendiente', help_text='"pendiente", "entregado", "finalizado"', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVentaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio actual del producto', max_digits=10)),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productoterminado')),
                ('venta_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.ventacliente')),
            ],
        ),
    ]
