# Generated by Django 5.1.7 on 2025-03-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_cliente/'),
        ),
        migrations.AlterField(
            model_name='gramajeproductoterminado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_gramajeProductoTerminado/'),
        ),
        migrations.AlterField(
            model_name='presentacionproductoterminado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_presentacionProductoTerminado/'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_productoTerminado/'),
        ),
    ]
