# Generated by Django 5.1.7 on 2026-02-23 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductoGranel', '0002_initial'),
        ('ProductoTerminado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corteinventariopterminado',
            name='usuario',
            field=models.ForeignKey(help_text='Quién realizó el corte', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleconcentradopedidos',
            name='concentrado_pedidos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.concentradopedidos'),
        ),
        migrations.AddField(
            model_name='detallecorteinventariopterminado',
            name='corte_inventario_p_terminado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.corteinventariopterminado'),
        ),
        migrations.AddField(
            model_name='entradapterminado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleentradapterminado',
            name='entrada_p_terminado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.entradapterminado'),
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='categoria_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='inventarioruta',
            name='producto_terminado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productoterminado'),
        ),
        migrations.AddField(
            model_name='detalleventacliente',
            name='producto_terminado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productoterminado'),
        ),
        migrations.AddField(
            model_name='detallesalidapterminado',
            name='producto_terminado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productoterminado'),
        ),
        migrations.AddField(
            model_name='detallecorteinventariopterminado',
            name='producto_terminado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productoterminado'),
        ),
        migrations.AddField(
            model_name='detalleconcentradopedidos',
            name='producto_terminado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productoterminado'),
        ),
        migrations.AddField(
            model_name='productovariacion',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.presentacionproductoterminado'),
        ),
        migrations.AddField(
            model_name='productovariacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaciones', to='ProductoTerminado.productoterminado'),
        ),
        migrations.AddField(
            model_name='detalleentradapterminado',
            name='producto_variacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productovariacion'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventarioruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.ruta'),
        ),
        migrations.AddField(
            model_name='concentradopedidos',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProductoTerminado.ruta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProductoTerminado.ruta'),
        ),
        migrations.AddField(
            model_name='salidapterminado',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProductoTerminado.ruta'),
        ),
        migrations.AddField(
            model_name='salidapterminado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallesalidapterminado',
            name='salida_p_terminado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.salidapterminado'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.vehiculo'),
        ),
        migrations.AddField(
            model_name='ventacliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.cliente'),
        ),
        migrations.AddField(
            model_name='ventacliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleventacliente',
            name='venta_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.ventacliente'),
        ),
    ]
