# Generated by Django 5.1.7 on 2026-03-31 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesalidapterminado',
            name='producto_terminado',
        ),
        migrations.AddField(
            model_name='detallesalidapterminado',
            name='producto_variacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productovariacion'),
            preserve_default=False,
        ),
    ]
