# Generated by Django 5.1.7 on 2026-04-24 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0003_remove_detallesalidapterminado_producto_terminado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleconcentradopedidos',
            name='concentrado_pedidos',
        ),
        migrations.RemoveField(
            model_name='corteinventariopterminado',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='detallecorteinventariopterminado',
            name='corte_inventario_p_terminado',
        ),
        migrations.RemoveField(
            model_name='detalleconcentradopedidos',
            name='producto_terminado',
        ),
        migrations.RemoveField(
            model_name='detallecorteinventariopterminado',
            name='producto_terminado',
        ),
        migrations.RemoveField(
            model_name='detalleventacliente',
            name='producto_terminado',
        ),
        migrations.RemoveField(
            model_name='detalleventacliente',
            name='venta_cliente',
        ),
        migrations.RemoveField(
            model_name='ventacliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ventacliente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='inventarioruta',
            name='producto_terminado',
        ),
        migrations.AddField(
            model_name='inventarioruta',
            name='producto_variacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productovariacion'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConcentradoPedidos',
        ),
        migrations.DeleteModel(
            name='CorteInventarioPTerminado',
        ),
        migrations.DeleteModel(
            name='DetalleConcentradoPedidos',
        ),
        migrations.DeleteModel(
            name='DetalleCorteInventarioPTerminado',
        ),
        migrations.DeleteModel(
            name='DetalleVentaCliente',
        ),
        migrations.DeleteModel(
            name='VentaCliente',
        ),
    ]
