# Generated by Django 5.1.7 on 2025-03-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0003_remove_productoterminado_gramaje_producto_terminado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioproductoterminado',
            name='stock_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
