# Generated by Django 5.1.7 on 2025-03-24 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0004_inventarioproductoterminado_stock_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoterminado',
            name='gramaje_producto_terminado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.gramajeproductoterminado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='stock_min',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InventarioProductoTerminado',
        ),
    ]
