# Generated by Django 5.1.7 on 2025-03-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0005_productoterminado_gramaje_producto_terminado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidapterminado',
            name='destino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salidapterminado',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
