# Generated by Django 5.1.7 on 2026-04-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0005_cliente_updated_at_clientediasvisita_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
