# Generated by Django 5.1.7 on 2026-05-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0006_cliente_porcentaje_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='credito',
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto máximo que se le puede fiar', max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_adeudo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cuánto debe el cliente actualmente', max_digits=10),
        ),
    ]
