# Generated by Django 5.1.7 on 2025-03-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0006_alter_salidapterminado_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_vehiculos/'),
        ),
        migrations.AlterField(
            model_name='salidapterminado',
            name='destino',
            field=models.CharField(choices=[('opcion1', 'Ruta'), ('opcion2', 'Mitsu'), ('opcion3', 'Maestro'), ('opcion3', 'Otros')], default='opcion1', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
