# Generated by Django 5.1.7 on 2026-09-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0007_remove_cliente_credito_cliente_limite_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesalidapterminado',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
