# Generated by Django 5.1.7 on 2025-03-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0007_vehiculo_imagen_alter_salidapterminado_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='ultimo_servicio',
            field=models.DateField(),
        ),
    ]
