# Generated by Django 5.1.7 on 2026-09-24 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0008_detallesalidapterminado_precio_unitario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteInventarioPTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('correcto', 'Correcto'), ('ajustado', 'Ajustado')], default='correcto', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCorteInventarioPTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_teorico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ajuste_necesario', models.BooleanField(default=False)),
                ('corte_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.corteinventariopterminado')),
                ('producto_variacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productovariacion')),
            ],
        ),
    ]
