# Generated by Django 5.1.7 on 2025-03-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0008_alter_vehiculo_ultimo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
