# Generated by Django 5.1.7 on 2026-09-29 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0009_corteinventariopterminado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreccionPTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_correccion', models.CharField(choices=[('producto', 'Producto incorrecto'), ('cantidad', 'Cantidad incorrecta'), ('eliminar', 'Eliminar producto')], max_length=20)),
                ('cantidad_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_nueva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_correccion', models.DateTimeField(auto_now_add=True)),
                ('detalle_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones', to='ProductoTerminado.detalleentradapterminado')),
                ('detalle_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones', to='ProductoTerminado.detallesalidapterminado')),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correcciones', to='ProductoTerminado.entradapterminado')),
                ('producto_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_como_anterior', to='ProductoTerminado.productovariacion')),
                ('producto_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_como_nuevo', to='ProductoTerminado.productovariacion')),
                ('salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correcciones', to='ProductoTerminado.salidapterminado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
