# Generated by Django 5.1.7 on 2025-03-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0009_vehiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
