# Generated by Django 5.1.7 on 2025-03-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0011_alter_cliente_colonia_alter_cliente_credito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientediasvisita',
            name='dia_semana',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], max_length=255),
        ),
    ]
