# Generated by Django 5.1.7 on 2025-03-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0012_alter_clientediasvisita_dia_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentradopedidos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='ventacliente',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pendiente', max_length=50),
        ),
    ]
