# Generated by Django 5.1.7 on 2025-05-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0016_alter_corteinventariopterminado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacionproductoterminado',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
