# Generated by Django 5.1.7 on 2025-05-07 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0017_alter_presentacionproductoterminado_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventacliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.cliente'),
        ),
        migrations.CreateModel(
            name='DetalleInventarioRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productoterminado')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.ruta')),
            ],
        ),
    ]
