# Generated by Django 5.1.7 on 2025-05-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0018_alter_ventacliente_cliente_detalleinventarioruta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleInventarioRuta',
        ),
    ]
