# Generated by Django 5.1.7 on 2025-05-15 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0019_delete_detalleinventarioruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventacliente',
            name='observaciones',
        ),
    ]
