# Generated by Django 5.1.7 on 2025-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0020_remove_ventacliente_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventacliente',
            name='stock_descontado',
            field=models.BooleanField(default=False, help_text='¿Se ha restado ya el stock para esta venta?'),
        ),
    ]
