# Generated by Django 5.1.7 on 2025-06-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0021_ventacliente_stock_descontado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidapterminado',
            name='destino',
            field=models.CharField(choices=[('opcion1', 'Ruta'), ('opcion2', 'Mitsu'), ('opcion3', 'Maestro'), ('opcion4', 'Otros')], default='opcion1', max_length=255),
        ),
    ]
