# Generated by Django 5.1.7 on 2026-02-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos_categoriaProductos/')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorteInventarioGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('correcto', 'Correcto'), ('ajustado', 'Ajustado')], default='correcto', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCorteInventarioGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_teorico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ajuste_necesario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDevolucionGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEntradaGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedidoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSalidaGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_caducidad', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('estado_lote', models.CharField(choices=[('activo', 'Activo'), ('agotado', 'Agotado'), ('caducado', 'Caducado')], default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('procesado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_produccion', 'En Producción'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_caducidad', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos_productoGranel/')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('destino', models.CharField(max_length=255)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
