# Generated by Django 5.1.7 on 2025-03-15 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorteInventarioGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('verificado', 'Verificado'), ('ajustado', 'Ajustado')], default='pendiente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_caducidad', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.categoriaproducto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_caducidad', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('estado_lote', models.CharField(choices=[('activo', 'Activo'), ('agotado', 'Agotado'), ('caducado', 'Caducado')], default='activo', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.productogranel')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEntradaGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.entradagranel')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.productogranel')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDevolucionGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.devoluciongranel')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.productogranel')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCorteInventarioGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_teorico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ajuste_necesario', models.BooleanField(default=False)),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.corteinventariogranel')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.productogranel')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('destino', models.CharField(max_length=255)),
                ('nota', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='devoluciongranel',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.salidagranel'),
        ),
        migrations.CreateModel(
            name='DetalleSalidaGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.productogranel')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.salidagranel')),
            ],
        ),
    ]
