# Generated by Django 5.1.7 on 2026-02-23 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductoGranel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corteinventariogranel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallecorteinventariogranel',
            name='corte_inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.corteinventariogranel'),
        ),
        migrations.AddField(
            model_name='detalledevoluciongranel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallepedidoproduccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devoluciongranel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalledevoluciongranel',
            name='devolucion_granel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.devoluciongranel'),
        ),
        migrations.AddField(
            model_name='entradagranel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleentradagranel',
            name='entrada_granel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.entradagranel'),
        ),
        migrations.AddField(
            model_name='detallesalidagranel',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.lote'),
        ),
        migrations.AddField(
            model_name='detalledevoluciongranel',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.lote'),
        ),
        migrations.AddField(
            model_name='pedidoproduccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallepedidoproduccion',
            name='pedido_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.pedidoproduccion'),
        ),
        migrations.AddField(
            model_name='productogranel',
            name='categoria_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='producto_granel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.productogranel'),
        ),
        migrations.AddField(
            model_name='detallesalidagranel',
            name='producto_granel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.productogranel'),
        ),
        migrations.AddField(
            model_name='detallepedidoproduccion',
            name='producto_granel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.productogranel'),
        ),
        migrations.AddField(
            model_name='detalleentradagranel',
            name='producto_granel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.productogranel'),
        ),
        migrations.AddField(
            model_name='detalledevoluciongranel',
            name='producto_granel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.productogranel'),
        ),
        migrations.AddField(
            model_name='detallecorteinventariogranel',
            name='producto_granel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.productogranel'),
        ),
        migrations.AddField(
            model_name='productogranel',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.proveedor'),
        ),
        migrations.AddField(
            model_name='salidagranel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devoluciongranel',
            name='salida_granel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.salidagranel'),
        ),
        migrations.AddField(
            model_name='detallesalidagranel',
            name='salida_granel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoGranel.salidagranel'),
        ),
    ]
