# Generated by Django 5.1.7 on 2026-04-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoGranel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
