# Generated by Django 5.1.7 on 2025-03-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoGranel', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_categoriaProductos/'),
        ),
        migrations.AlterField(
            model_name='productogranel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_productoGranel/'),
        ),
    ]
