# Generated by Django 5.1.7 on 2025-03-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoGranel', '0004_alter_categoriaproducto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corteinventariogranel',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('correcto', 'Correcto'), ('ajustado', 'Ajustado')], default='correcto', max_length=20),
        ),
    ]
