# Generated by Django 5.1.7 on 2025-05-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoGranel', '0005_alter_corteinventariogranel_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
