# Generated by Django 5.1.7 on 2026-04-24 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductoTerminado', '0005_cliente_updated_at_clientediasvisita_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='MiniBodegaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mini_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovil.minibodega')),
                ('producto_variacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productovariacion')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoReabastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.ruta')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoReabastecimientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovil.pedidoreabastecimiento')),
                ('producto_variacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productovariacion')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sincronizado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProductoTerminado.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_variacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productovariacion')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovil.venta')),
            ],
        ),
    ]
