# Generated by Django 5.1.7 on 2026-05-11 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0006_cliente_porcentaje_descuento'),
        ('appMovil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('sincronizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProductoTerminado.cliente')),
                ('mini_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovil.minibodega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovil.devolucion')),
                ('producto_variacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productovariacion')),
            ],
        ),
        migrations.CreateModel(
            name='MiniBodegaDetalleMerma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMovil.devolucion')),
                ('mini_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovil.minibodega')),
                ('producto_variacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productovariacion')),
            ],
        ),
    ]
