# Generated by Django 5.1.7 on 2026-09-25 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovil', '0007_dispositivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteInventarioMiniBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('correcto', 'Correcto'), ('ajustado', 'Ajustado')], default='correcto', max_length=20)),
                ('mini_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovil.minibodega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCorteInventarioMiniBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_teorico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ajuste_necesario', models.BooleanField(default=False)),
                ('corte_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovil.corteinventariominibodega')),
                ('mini_bodega_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovil.minibodegadetalle')),
            ],
        ),
    ]
