# Generated by Django 5.1.7 on 2026-10-03 22:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0010_correccionpterminado'),
        ('appMovil', '0009_cancelacionventa_cancelacionventadetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionSustitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sincronizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovil.devolucion')),
                ('devolucion_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovil.devoluciondetalle')),
                ('producto_sustituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoTerminado.productovariacion')),
            ],
        ),
    ]
