# Generated by Django 5.1.7 on 2026-10-06 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0010_correccionpterminado'),
        ('appMovil', '0010_devolucionsustitucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelacionDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('devolucion_uuid', models.UUIDField()),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mini_bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appMovil.minibodega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CancelacionDevolucionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('cancelacion_uuid', models.UUIDField()),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='appMovil.cancelaciondevolucion')),
                ('producto_variacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ProductoTerminado.productovariacion')),
            ],
        ),
        migrations.CreateModel(
            name='CancelacionDevolucionSustitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('cancelacion_uuid', models.UUIDField()),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustituciones', to='appMovil.cancelaciondevolucion')),
                ('producto_variacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ProductoTerminado.productovariacion')),
            ],
        ),
    ]
