# Generated by Django 5.1.7 on 2026-10-09 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0010_correccionpterminado'),
        ('appMovil', '0011_cancelaciondevolucion_cancelaciondevoluciondetalle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField()),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ProductoTerminado.cliente')),
                ('mini_bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appMovil.minibodega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RotacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('producto_variacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ProductoTerminado.productovariacion')),
                ('rotacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovil.rotacion')),
            ],
        ),
        migrations.CreateModel(
            name='RotacionSustitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField()),
                ('sincronizado', models.BooleanField(default=False)),
                ('producto_variacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ProductoTerminado.productovariacion')),
                ('rotacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovil.rotacion')),
                ('rotacion_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovil.rotaciondetalle')),
            ],
        ),
    ]
