# Generated by Django 5.1.7 on 2026-10-10 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovil', '0012_rotacion_rotaciondetalle_rotacionsustitucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoreabastecimiento',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoreabastecimiento',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoreabastecimiento',
            name='resultado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADO', 'Procesado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='pedidoreabastecimiento',
            name='usuario_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_reabastecimiento_cerrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
