# Generated by Django 5.1.7 on 2026-10-10 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoTerminado', '0010_correccionpterminado'),
        ('appMovil', '0013_pedidoreabastecimiento_fecha_cierre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoReabastecimientoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('AGREGAR', 'Producto agregado'), ('MODIFICAR', 'Producto modificado'), ('ELIMINAR', 'Producto eliminado'), ('RECHAZAR', 'Pedido rechazado')], max_length=15)),
                ('cantidad_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_nueva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='appMovil.pedidoreabastecimiento')),
                ('producto_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ProductoTerminado.productovariacion')),
                ('producto_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ProductoTerminado.productovariacion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
